name: in_app_translator
description: "A lightweight Flutter localization manager that provides multi-locale support, automatic caching,
background translations, fallback locales, and easy integration via a flexible delegate system."
version: 1.0.2
repository: https://github.com/Mohiuddin655-PUB/in_app_translator

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
